apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    # Access mode - proxy (server in the UI) or direct (browser in the UI).
    url: http://172.20.0.1:9090
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus